# Generated by Django 2.2.7 on 2019-12-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='Longitude')),
                ('y', models.FloatField(help_text='Latitude')),
                ('ID', models.CharField(help_text='Unique Squirrel Id', max_length=50)),
                ('shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='shift', max_length=50)),
                ('date', models.CharField(help_text='date', max_length=50)),
                ('age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=50, null=True)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=50, null=True)),
                ('location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=50, null=True)),
                ('specific_Location', models.CharField(help_text='Specific Location', max_length=50, null=True)),
                ('running', models.CharField(help_text='Running?', max_length=50)),
                ('chasing', models.CharField(help_text='Chasing?', max_length=50)),
                ('climbing', models.CharField(help_text='Climbing?', max_length=50)),
                ('eating', models.CharField(help_text='Eating?', max_length=50)),
                ('foraging', models.CharField(help_text='Foraging?', max_length=50)),
                ('other_activities', models.CharField(help_text='Other Activities', max_length=50, null=True)),
                ('kuks', models.CharField(help_text='Kuks?', max_length=50)),
                ('quaas', models.CharField(help_text='Quaas?', max_length=50)),
                ('tail_flags', models.CharField(help_text='Tail Flags?', max_length=50)),
                ('tail_twitches', models.CharField(help_text='Tail Twitches?', max_length=50)),
                ('approaches', models.CharField(help_text='Approaches?', max_length=50)),
                ('Indifferent', models.CharField(help_text='Indifferent?', max_length=50)),
                ('runs_from', models.CharField(help_text='Runs From?', max_length=50)),
                ('other_interactions', models.CharField(help_text='Others Interactions', max_length=50, null=True)),
                ('hectare', models.CharField(help_text='Hectare', max_length=50)),
                ('hectare_squirrel_Number', models.CharField(help_text='Squirrel Number', max_length=50)),
                ('latlong', models.CharField(help_text='LatLong Point', max_length=50)),
                ('highlight_fur_color', models.CharField(help_text='Highlight Fur Color', max_length=50)),
                ('color_note', models.CharField(help_text='Color Note', max_length=50)),
                ('combination_of_primary_and_highlight_color', models.CharField(help_text='Combination of Primary and Highlight', max_length=50)),
                ('above_ground_sighter_measurement', models.CharField(help_text='Above Ground Sighter Measurement', max_length=50, null=True)),
                ('moans', models.CharField(help_text='Moans', max_length=50)),
            ],
        ),
    ]
