# Generated by Django 2.2.7 on 2019-12-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracker',
            name='ID',
            field=models.CharField(help_text='Unique Squirrel Id', max_length=50, primary_key=True, serialize=False),
        ),
    ]
