# Generated by Django 2.2.7 on 2019-12-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191208_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='ID',
            new_name='unique_squirrel_id',
        ),
    ]
